package com.finora.brain;

import com.finora.model.Debt;
import com.finora.model.TransactionRecord;
import com.finora.service.FinanceService;
import com.finora.util.Money;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class FinoraBrain {
    public record BrainState(FinancialSnapshot snapshot,SafeToSpendResult safeToSpend,MonthlyPlan monthlyPlan,
                             HealthScore health,List<Recommendation> recommendations,ForecastEngine.Forecast forecast){}
    private static final Pattern AMOUNT=Pattern.compile("(?:₹|rs\\.?\\s*)?([0-9][0-9,]*(?:\\.[0-9]{1,2})?)",Pattern.CASE_INSENSITIVE);
    private final FinanceService finance;
    private final CashFlowEngine cashFlow=new CashFlowEngine();
    private final BudgetEngine budget=new BudgetEngine();
    private final DebtEngine debt=new DebtEngine();
    private final EMIEngine emi=new EMIEngine();
    private final GoalEngine goals=new GoalEngine();
    private final InvestmentEngine investment=new InvestmentEngine();
    private final ForecastEngine forecast=new ForecastEngine();
    private final FinancialHealthEngine health=new FinancialHealthEngine();
    private final RecommendationEngine recommendation=new RecommendationEngine();

    public FinoraBrain(FinanceService finance){this.finance=Objects.requireNonNull(finance);}
    public BrainState analyze() throws SQLException {
        FinancialSnapshot s=cashFlow.snapshot(finance,LocalDate.now());SafeToSpendResult safe=budget.safeToSpend(s);HealthScore score=health.calculate(s);
        return new BrainState(s,safe,budget.createPlan(s),score,recommendation.generate(s,safe,score),forecast.daily(s,30));
    }
    public BrainResponse ask(String question)throws SQLException{
        if(question==null||question.isBlank())return insufficient("Ask a question about your local financial records.");
        String q=question.toLowerCase(Locale.ROOT);BrainState state=analyze();FinancialSnapshot s=state.snapshot();
        if(q.contains("safe")||q.contains("how much can i spend")||q.contains("spend today"))return safeResponse(state);
        if(q.contains("afford")||q.contains("purchase")||q.contains("buy")){Optional<BigDecimal> amount=extractAmount(question);return amount.map(a->affordability(state,a)).orElseGet(()->insufficient("Include the purchase amount so I can test affordability."));}
        if(q.contains("who")&&q.contains("pay")||q.contains("pay first")||q.contains("priority debt"))return debtPriority(state);
        if(q.contains("how much debt")||q.contains("total debt"))return new BrainResponse("CALCULATED FACT",Money.inr(s.liabilities())+" total debt","This is the sum of all active recorded liabilities.",List.of("Active debts: "+s.debts().size(),"Minimum commitments: "+Money.inr(s.debts().stream().map(Debt::minimumPayment).reduce(BigDecimal.ZERO,BigDecimal::add))),List.of("Open Debt Center to inspect every balance."),List.of("Balances are only as current as your last recorded payments."),Recommendation.Severity.ATTENTION);
        if(q.contains("debt free")||q.contains("debt-free"))return debtFree(state);
        if(q.contains("health")||q.contains("score low"))return healthResponse(state);
        if(q.contains("biggest expense")||q.contains("top expense"))return biggestExpenses(state);
        if(q.contains("how much should i save")||q.contains("save this month"))return savingsResponse(state);
        if(q.contains("income")&&(q.contains("decrease")||q.contains("drop")||q.contains("lose")))return incomeShock(state,question);
        if((q.contains("repay")||q.contains("debt"))&&q.contains("invest"))return debtVsInvest(state);
        if(q.contains("emi"))return emiCapacity(state);
        if(q.contains("bill")||q.contains("coming this week"))return upcomingBills(state);
        if(q.contains("six months")||q.contains("6 months")||q.contains("forecast"))return forecastResponse(state);
        return insufficient("I can calculate safe spending, affordability, debt priority, debt-free timing, savings, bills, forecasts, health, income shocks and EMI capacity from your records.");
    }

    private BrainResponse safeResponse(BrainState st){FinancialSnapshot s=st.snapshot();SafeToSpendResult x=st.safeToSpend();return new BrainResponse("SAFE TO SPEND",Money.inr(x.today())+" today","This is a conservative daily allowance for the rest of the current month.",List.of("Planned monthly income  "+Money.inr(s.monthlyIncome()),"Received this month  "+Money.inr(s.recordedIncome()),"Recorded outflow  "+Money.inr(s.monthlyOutflow()),"Upcoming bills  "+Money.inr(s.upcomingBills()),"Debt commitments  "+Money.inr(s.upcomingDebtCommitments()),"Protected reserve  "+Money.inr(x.protectedReserve()),"Flexible remainder  "+Money.inr(x.flexibleRemaining())),List.of("Recalculate after adding a transaction or changing an obligation."),List.of("Active recurring income schedules, bills and due dates are assumed to remain configured.","This is an educational planning limit, not a guarantee that spending is risk-free."),x.today().signum()>0?Recommendation.Severity.HEALTHY:Recommendation.Severity.WARNING);}
    private BrainResponse affordability(BrainState st,BigDecimal purchase){FinancialSnapshot s=st.snapshot();SafeToSpendResult x=st.safeToSpend();boolean within= purchase.compareTo(x.flexibleRemaining())<=0;boolean cash=s.cash().compareTo(purchase)>=0;String headline=within?"Comfortable within this month's flexible capacity":cash?"Proceed carefully":"Not currently supported by recorded cash";Recommendation.Severity severity=within?Recommendation.Severity.HEALTHY:cash?Recommendation.Severity.WARNING:Recommendation.Severity.CRITICAL;List<String> rec=within?List.of("If the purchase is necessary, it fits the current flexible envelope."):cash?List.of("Consider saving "+Money.inr(purchase.divide(new BigDecimal("5"),2,RoundingMode.CEILING))+" per month for five months.","Or reassess after the next recorded income cycle."):List.of("Build a dedicated goal instead of using protected funds.");return new BrainResponse("AFFORDABILITY",headline,"Purchase tested: "+Money.inr(purchase),List.of("Available operating cash  "+Money.inr(s.cash()),"Flexible remainder  "+Money.inr(x.flexibleRemaining()),"Emergency reserve  "+Money.inr(s.emergencyFund()),"Upcoming obligations  "+Money.inr(s.upcomingBills().add(s.upcomingDebtCommitments()))),rec,List.of("No unrecorded income, financing cost or resale value is assumed.","FINORA explains trade-offs; the decision remains yours."),severity);}
    private BrainResponse debtPriority(BrainState st){if(st.snapshot().debts().isEmpty())return insufficient("No active debts are recorded.");DebtEngine.StrategyAdvice advice=debt.recommendStrategy(st.snapshot().debts(),LocalDate.now());List<DebtEngine.PrioritizedDebt> ranked=debt.prioritize(st.snapshot().debts(),advice.strategy(),LocalDate.now());Debt first=ranked.getFirst().debt();List<String> calc=new ArrayList<>();for(int i=0;i<Math.min(4,ranked.size());i++){var p=ranked.get(i);calc.add("#"+(i+1)+"  "+p.debt().name()+" · "+Money.inr(p.debt().remainingAmount())+" — "+p.reason());}return new BrainResponse("RECOMMENDED ORDER","Pay "+first.name()+" first",advice.explanation(),calc,List.of("Protect minimum payments on every obligation before sending extra money to the first-ranked debt."),List.of("Ranking uses the stored due dates, rates, penalty risk, relationship importance and manual priority.","You can override this order in Debt Center."),Recommendation.Severity.WARNING);}
    private BrainResponse debtFree(BrainState st){BigDecimal payment=st.monthlyPlan().debtAndEmi();DebtEngine.DebtForecast f=debt.forecast(st.snapshot().debts(),payment);if(f.months()<0||f.debtFreeMonth()==null)return insufficient("Set a sustainable monthly debt payment to calculate a debt-free date.");return new BrainResponse("DEBT-FREE FORECAST",f.debtFreeMonth().getMonth()+" "+f.debtFreeMonth().getYear(),"Estimated from the plan's monthly debt allocation.",List.of("Current debt  "+Money.inr(st.snapshot().liabilities()),"Monthly payment assumption  "+Money.inr(payment),"Estimated interest  "+Money.inr(f.estimatedInterest()),"Estimated duration  "+f.months()+" months"),List.of("Paying extra can shorten the estimate; use the Debt Center simulator to compare."),List.of("Rates and monthly payment are assumed constant.","Fees, late penalties and rate changes are excluded unless recorded."),Recommendation.Severity.ATTENTION);}
    private BrainResponse healthResponse(BrainState st){HealthScore h=st.health();List<String> factors=h.factors().entrySet().stream().map(e->e.getKey()+"  "+e.getValue()+"/100").toList();String weakest=h.factors().entrySet().stream().min(Map.Entry.comparingByValue()).map(Map.Entry::getKey).orElse("records");return new BrainResponse("FINANCIAL HEALTH",h.overall()+" / 100 · "+h.label(),"The lowest contributing area is "+weakest+".",factors,List.of("Improve the lowest factor first; it has the clearest effect on the internal score."),List.of("This is an educational FINORA score, not a credit score or professional financial rating."),h.overall()>=70?Recommendation.Severity.HEALTHY:Recommendation.Severity.WARNING);}
    private BrainResponse biggestExpenses(BrainState st){if(st.snapshot().expenseByCategory().isEmpty())return insufficient("No expenses are recorded for this month.");List<Map.Entry<String,BigDecimal>> sorted=st.snapshot().expenseByCategory().entrySet().stream().sorted(Map.Entry.<String,BigDecimal>comparingByValue().reversed()).toList();return new BrainResponse("SPENDING ANALYSIS",sorted.getFirst().getKey()+" is the largest category","Recorded category total: "+Money.inr(sorted.getFirst().getValue()),sorted.stream().limit(5).map(e->e.getKey()+"  "+Money.inr(e.getValue())).toList(),List.of("Review the category detail before changing its budget."),List.of("Only transactions recorded in the current calendar month are included."),Recommendation.Severity.ATTENTION);}
    private BrainResponse savingsResponse(BrainState st){MonthlyPlan p=st.monthlyPlan();BigDecimal total=p.emergencySavings().add(p.goals()).add(p.investments()).add(p.reserve());return new BrainResponse("SAVINGS CAPACITY",Money.inr(total)+" planned this month","The amount is allocated only after essentials and debt/EMI commitments.",List.of("Emergency savings  "+Money.inr(p.emergencySavings()),"Goals  "+Money.inr(p.goals()),"Long-term allocation  "+Money.inr(p.investments()),"Cash reserve  "+Money.inr(p.reserve())),List.of("Edit the monthly plan if your income is variable or an obligation is missing."),List.of("Assumes monthly income remains "+Money.inr(p.income())+".","Investment allocation is educational and has no guaranteed return."),Recommendation.Severity.HEALTHY);}
    private BrainResponse incomeShock(BrainState st,String question){BigDecimal amount=extractAmount(question).orElse(st.snapshot().monthlyIncome().multiply(new BigDecimal("0.20")));if(question.contains("%")){amount=st.snapshot().monthlyIncome().multiply(amount.divide(new BigDecimal("100"),6,RoundingMode.HALF_UP));}BigDecimal newIncome=st.snapshot().monthlyIncome().subtract(amount).max(BigDecimal.ZERO);BigDecimal present=st.monthlyPlan().flexible().add(st.monthlyPlan().reserve());BigDecimal impact=amount.min(present);return new BrainResponse("INCOME SHOCK SCENARIO",Money.inr(newIncome)+" revised monthly income","A reduction of "+Money.inr(amount)+" would first absorb flexible capacity and reserve.",List.of("Current income  "+Money.inr(st.snapshot().monthlyIncome()),"Revised income  "+Money.inr(newIncome),"Flexible capacity affected  "+Money.inr(impact),"Recorded obligations  "+Money.inr(st.snapshot().upcomingBills().add(st.snapshot().upcomingDebtCommitments()))),List.of(amount.compareTo(present)>0?"The shock exceeds flexible capacity. Review goals and creditor timing before it occurs.":"The current plan can absorb this shock without changing recorded essential costs."),List.of("The scenario does not modify real data.","Expenses and obligations are held constant."),amount.compareTo(present)>0?Recommendation.Severity.CRITICAL:Recommendation.Severity.WARNING);}
    private BrainResponse debtVsInvest(BrainState st){Optional<Debt> costly=st.snapshot().debts().stream().max(Comparator.comparing(Debt::interestRate));boolean reserveReady=st.snapshot().emergencyFund().compareTo(st.snapshot().essentialExpenses().multiply(new BigDecimal("3")))>=0;boolean repay=costly.isPresent()&&(!reserveReady||costly.get().interestRate().compareTo(new BigDecimal("8"))>0);return new BrainResponse("DECISION ANALYSIS",repay?"Prioritize debt repayment":"A split allocation may be reasonable",repay?"The recorded debt cost and reserve position take priority over uncertain returns.":"Your emergency reserve is funded and recorded debt cost is moderate.",List.of("Highest debt rate  "+costly.map(d->d.interestRate().stripTrailingZeros().toPlainString()+"%").orElse("0%"),"Emergency reserve  "+Money.inr(st.snapshot().emergencyFund()),"Three-month target  "+Money.inr(st.snapshot().essentialExpenses().multiply(new BigDecimal("3")))),List.of(repay?"Protect minimums, then direct available extra money to the priority debt.":"Choose your own investment assumptions and risk tolerance before allocating."),List.of("Debt cost is known from your records; investment returns are uncertain and not guaranteed.","This is educational analysis, not regulated investment advice."),Recommendation.Severity.ATTENTION);}
    private BrainResponse emiCapacity(BrainState st){BigDecimal room=st.monthlyPlan().flexible().subtract(st.monthlyPlan().reserve()).max(BigDecimal.ZERO);return new BrainResponse("EMI CAPACITY",room.signum()>0?"Up to "+Money.inr(room)+" is visible in the current plan":"No additional EMI capacity is visible","FINORA does not recommend using the entire amount; a new EMI would reduce flexibility every month.",List.of("Plan flexible amount  "+Money.inr(st.monthlyPlan().flexible()),"Protected cash reserve  "+Money.inr(st.monthlyPlan().reserve()),"Existing debt allocation  "+Money.inr(st.monthlyPlan().debtAndEmi())),List.of("Test the exact EMI in Scenario Planner before committing."),List.of("Income and essential costs are assumed stable.","Lender eligibility, fees and credit decisions are not assessed."),room.signum()>0?Recommendation.Severity.ATTENTION:Recommendation.Severity.WARNING);}
    private BrainResponse upcomingBills(BrainState st){var bills=st.snapshot().bills().stream().filter(b->!b.paid()).sorted(Comparator.comparing(b->b.dueDate())).toList();if(bills.isEmpty())return insufficient("No unpaid bills are recorded for the rest of this month.");return new BrainResponse("UPCOMING OBLIGATIONS",Money.inr(st.snapshot().upcomingBills())+" in recorded bills","There are "+bills.size()+" unpaid bill"+(bills.size()==1?"":"s")+" before month end.",bills.stream().map(b->b.dueDate()+" · "+b.name()+"  "+Money.inr(b.amount())).toList(),List.of("Keep these amounts protected in your operating account."),List.of("Recurring bills beyond their currently stored due date are not included here."),Recommendation.Severity.ATTENTION);}
    private BrainResponse forecastResponse(BrainState st){ForecastEngine.Forecast f=st.forecast();return new BrainResponse("30-DAY FORECAST",Money.inr(f.projectedEndingBalance())+" projected operating balance",f.firstPressureDate()==null?"No reserve pressure is detected from configured events.":"Reserve pressure may begin around "+f.firstPressureDate()+".",List.of("Starting cash  "+Money.inr(st.snapshot().cash()),"Projected ending cash  "+Money.inr(f.projectedEndingBalance()),"Upcoming bills  "+Money.inr(st.snapshot().upcomingBills()),"Upcoming debt commitments  "+Money.inr(st.snapshot().upcomingDebtCommitments())),List.of("Add missing recurring events to improve the forecast."),List.of(f.assumption()),f.firstPressureDate()==null?Recommendation.Severity.HEALTHY:Recommendation.Severity.WARNING);}
    private static Optional<BigDecimal> extractAmount(String text){Matcher m=AMOUNT.matcher(text);if(!m.find())return Optional.empty();try{return Optional.of(new BigDecimal(m.group(1).replace(",","")));}catch(NumberFormatException e){return Optional.empty();}}
    private static BrainResponse insufficient(String message){return new BrainResponse("MORE DATA NEEDED","I don't have enough information to calculate that.",message,List.of(),List.of("Add or update the relevant financial record, then ask again."),List.of("FINORA never invents missing financial values."),Recommendation.Severity.ATTENTION);}
}
