package com.finora.ai;

import com.finora.model.*;
import com.finora.service.FinanceService;
import com.finora.util.Money;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.regex.*;

/** Database-backed financial tools. All monetary arithmetic is deterministic BigDecimal math. */
public final class FinancialToolService {
    public record ToolResult(FinancialIntent intent,String answer,String toolTrace,List<String> missingData,boolean verified){}
    private final FinanceService finance;
    public FinancialToolService(FinanceService finance){this.finance=finance;}

    private record State(List<Account> accounts,List<IncomeSource> incomeSources,List<TransactionRecord> transactions,
                         List<Debt> debts,List<Goal> goals,List<Bill> bills,List<Budget> budgets,List<Investment> investments){
        BigDecimal totalBalance(){return accounts.stream().map(Account::balance).reduce(BigDecimal.ZERO,BigDecimal::add);}
        BigDecimal monthlyIncome(){return incomeSources.stream().filter(IncomeSource::active).map(IncomeSource::monthlyEquivalent).reduce(BigDecimal.ZERO,BigDecimal::add);}
        BigDecimal monthlyDebtPayments(){return debts.stream().map(Debt::minimumPayment).reduce(BigDecimal.ZERO,BigDecimal::add);}
        BigDecimal netWorth(){return totalBalance().add(investments.stream().map(Investment::currentValue).reduce(BigDecimal.ZERO,BigDecimal::add)).subtract(debts.stream().map(Debt::remainingAmount).reduce(BigDecimal.ZERO,BigDecimal::add));}
    }
    private State load()throws Exception{
        LocalDate now=LocalDate.now();
        return new State(finance.accounts(),finance.incomeSources(),finance.transactions(YearMonth.now()),finance.debts(),finance.goals(),
                finance.bills(now.minusMonths(1),now.plusYears(1)),finance.budgets(YearMonth.now()),finance.investments());
    }

    public ToolResult execute(long userId,FinancialIntent intent,String question)throws Exception{
        State s=load();return switch(intent){
            case BALANCE_QUERY->balances(s,intent);
            case NET_WORTH_QUERY->netWorth(s,intent);
            case INCOME_QUERY->income(s,intent);
            case EXPENSE_QUERY->expenses(s,intent);
            case TRANSACTION_QUERY->transactions(s,intent);
            case BUDGET_QUERY->budgets(s,intent);
            case DEBT_QUERY->debts(s,intent,question);
            case EMI_QUERY->emi(s,intent,question);
            case GOAL_QUERY,SAVINGS_QUERY->goals(s,intent);
            case BILL_QUERY,SUBSCRIPTION_QUERY->bills(s,intent);
            case INVESTMENT_QUERY->investments(s,intent);
            case AFFORDABILITY_QUERY->affordability(s,intent,question);
            case FORECAST_QUERY,SCENARIO_QUERY->forecast(s,intent,question);
            case FINANCIAL_HEALTH_QUERY->health(s,intent);
            case MONTHLY_PLAN_QUERY->plan(s,intent);
            default->general(s,intent);
        };}
    private ToolResult balances(State s,FinancialIntent i){if(s.accounts().isEmpty())return missing(i,"I cannot report a balance because no accounts are recorded yet.","accounts");StringBuilder b=new StringBuilder("## Current balances\n");for(Account a:s.accounts())b.append("- **").append(a.name()).append(":** ").append(Money.inr(a.balance())).append('\n');b.append("\n**Total cash and account assets: ").append(Money.inr(s.totalBalance())).append("**\n\nSource: current account records.");return ok(i,b,"accounts,totalBalance");}
    private ToolResult netWorth(State s,FinancialIntent i){if(s.accounts().isEmpty()&&s.debts().isEmpty()&&s.investments().isEmpty())return missing(i,"I need at least one account, debt, or investment record to calculate net worth.","accounts/debts/investments");BigDecimal cash=s.accounts().stream().map(Account::balance).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal invest=s.investments().stream().map(Investment::currentValue).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal liabilities=s.debts().stream().map(Debt::remainingAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal assets=cash.add(invest);String answer="## Net worth\n- Cash and accounts: **"+Money.inr(cash)+"**\n- Investments: **"+Money.inr(invest)+"**\n- Total assets: **"+Money.inr(assets)+"**\n- Liabilities: **"+Money.inr(liabilities)+"**\n\n### Verified result\n**"+Money.inr(assets)+" − "+Money.inr(liabilities)+" = "+Money.inr(assets.subtract(liabilities))+"**\n\nTransfers and goal earmarking do not change this result; real income, expenses, asset values, and liabilities do.";return ok(i,answer,"accounts+investments-debts");}
    private ToolResult income(State s,FinancialIntent i){BigDecimal actual=s.transactions().stream().filter(t->t.type()==TransactionRecord.TransactionType.INCOME&&isThisMonth(t.date())).map(TransactionRecord::amount).reduce(BigDecimal.ZERO,BigDecimal::add);if(s.incomeSources().isEmpty()&&actual.signum()==0)return missing(i,"No recurring income or income transactions are recorded for this month.","recurring income/income transactions");StringBuilder b=new StringBuilder("## Income snapshot\n- Income received this month: **").append(Money.inr(actual)).append("**\n- Scheduled monthly recurring income: **").append(Money.inr(s.monthlyIncome())).append("**\n");if(!s.incomeSources().isEmpty()){b.append("\n### Recurring sources\n");for(IncomeSource r:s.incomeSources())b.append("- ").append(r.name()).append(": ").append(Money.inr(r.amount())).append(" · ").append(r.frequency().label()).append(" · next ").append(date(r.nextIncomeDate())).append('\n');}b.append("\nScheduled income is kept separate from posted income, so it is not counted as cash until received.");return ok(i,b,"transactions,recurringIncomes");}
    private ToolResult expenses(State s,FinancialIntent i){List<TransactionRecord> list=s.transactions().stream().filter(t->t.type()==TransactionRecord.TransactionType.EXPENSE&&isThisMonth(t.date())).toList();if(list.isEmpty())return missing(i,"No expense transactions are recorded for this month, so I cannot identify a spending pattern yet.","expense transactions");Map<String,BigDecimal> categories=new HashMap<>();list.forEach(t->categories.merge(t.category(),t.amount(),BigDecimal::add));var sorted=categories.entrySet().stream().sorted(Map.Entry.<String,BigDecimal>comparingByValue().reversed()).toList();BigDecimal total=list.stream().map(TransactionRecord::amount).reduce(BigDecimal.ZERO,BigDecimal::add);StringBuilder b=new StringBuilder("## Spending this month\n**Total: ").append(Money.inr(total)).append("** across ").append(list.size()).append(" transactions.\n\n### By category\n");for(var e:sorted)b.append("- ").append(e.getKey()).append(": **").append(Money.inr(e.getValue())).append("**\n");b.append("\nLargest recorded category: **").append(sorted.getFirst().getKey()).append("**. This conclusion uses only posted transactions.");return ok(i,b,"current-month expense transactions grouped by category");}
    private ToolResult transactions(State s,FinancialIntent i){if(s.transactions().isEmpty())return missing(i,"There are no transactions to review yet.","transactions");StringBuilder b=new StringBuilder("## Recent transactions\n");s.transactions().stream().sorted(Comparator.comparing(TransactionRecord::date).reversed()).limit(8).forEach(t->b.append("- ").append(date(t.date())).append(" · ").append(t.description()).append(" · **").append(t.type()==TransactionRecord.TransactionType.EXPENSE?"−":"+").append(Money.inr(t.amount())).append("**\n"));return ok(i,b,"latest 8 transactions");}
    private ToolResult budgets(State s,FinancialIntent i){if(s.budgets().isEmpty())return missing(i,"No budgets are configured. Add a category limit to compare planned and actual spending.","budgets");Map<String,BigDecimal> spent=new HashMap<>();s.transactions().stream().filter(t->t.type()==TransactionRecord.TransactionType.EXPENSE&&isThisMonth(t.date())).forEach(t->spent.merge(t.category(),t.amount(),BigDecimal::add));StringBuilder b=new StringBuilder("## Budget check\n");for(Budget budget:s.budgets()){BigDecimal used=spent.getOrDefault(budget.category(),BigDecimal.ZERO),remaining=budget.limitAmount().subtract(used);b.append("- **").append(budget.category()).append(":** ").append(Money.inr(used)).append(" of ").append(Money.inr(budget.limitAmount())).append(" · ").append(remaining.signum()<0?"over by "+Money.inr(remaining.abs()):Money.inr(remaining)+" left").append('\n');}return ok(i,b,"budgets,current-month expenses");}
    private ToolResult emi(State s,FinancialIntent i,String q){List<BigDecimal> numbers=extractNumbers(q);if(numbers.size()<3){if(!s.debts().isEmpty())return debts(s,i,q);return missing(i,"For an EMI calculation, provide the principal, annual interest rate, and term in months — for example: “EMI for ₹5,00,000 at 8% for 60 months”.","principal/rate/months");}BigDecimal principal=numbers.get(0),annualRate=numbers.get(1);int months;try{months=numbers.get(2).intValueExact();}catch(ArithmeticException e){return missing(i,"The loan term must be a whole number of months.","whole-number term");}if(principal.signum()<=0||annualRate.signum()<0||months<=0||months>1200)return missing(i,"Use a positive principal, a non-negative annual rate, and a term between 1 and 1,200 months.","valid EMI inputs");MathContext mc=MathContext.DECIMAL128;BigDecimal payment;if(annualRate.signum()==0)payment=principal.divide(BigDecimal.valueOf(months),2,RoundingMode.HALF_UP);else{BigDecimal rate=annualRate.divide(new BigDecimal("1200"),mc),factor=BigDecimal.ONE.add(rate,mc).pow(months,mc);payment=principal.multiply(rate,mc).multiply(factor,mc).divide(factor.subtract(BigDecimal.ONE),mc).setScale(2,RoundingMode.HALF_UP);}BigDecimal total=payment.multiply(BigDecimal.valueOf(months)).setScale(2,RoundingMode.HALF_UP),interest=total.subtract(principal).setScale(2,RoundingMode.HALF_UP);String answer="## EMI calculation\n- Principal: **"+Money.inr(principal)+"**\n- Annual rate: **"+annualRate.stripTrailingZeros().toPlainString()+"%**\n- Term: **"+months+" months**\n- Monthly EMI: **"+Money.inr(payment)+"**\n- Total scheduled payments: "+Money.inr(total)+"\n- Total interest: "+Money.inr(interest)+"\n\nAssumptions: fixed rate, monthly compounding, payments at month end, and no fees, insurance, prepayments, penalties, or rate changes. This scenario does not alter your records.";return ok(i,answer,"BigDecimal amortization formula");}
    private ToolResult debts(State s,FinancialIntent i,String q){if(s.debts().isEmpty())return missing(i,"No debt records are available. Add the balance, annual interest rate, and payment to calculate a payoff path.","debts");List<Debt> sorted=s.debts().stream().sorted(Comparator.comparing(Debt::interestRate).reversed()).toList();BigDecimal total=sorted.stream().map(Debt::remainingAmount).reduce(BigDecimal.ZERO,BigDecimal::add);StringBuilder b=new StringBuilder("## Debt plan\n**Total outstanding: ").append(Money.inr(total)).append("**\n\n");for(Debt d:sorted)b.append("- **").append(d.name()).append(":** ").append(Money.inr(d.remainingAmount())).append(" at ").append(d.interestRate().stripTrailingZeros().toPlainString()).append("% · payment ").append(Money.inr(d.minimumPayment())).append(" · ").append(payoffEstimate(d)).append('\n');Debt first=sorted.getFirst();b.append("\n### Suggested order\nThe verified avalanche order starts with **").append(first.name()).append("** because it has the highest recorded rate. Keep minimum payments on the others. ");if(first.interestRate().signum()==0)b.append("All recorded rates are 0%, so prioritize cash-flow risk or smallest balance instead.");else b.append("This minimizes interest mathematically; choose smallest balance first only if motivation is more important.");return ok(i,b,"debts sorted by annual interest rate");}
    private ToolResult goals(State s,FinancialIntent i){if(s.goals().isEmpty())return missing(i,"No savings goals are recorded. Add a target, target date, and current earmarked amount for a pace calculation.","goals");StringBuilder b=new StringBuilder("## Goal progress\n");for(Goal g:s.goals()){BigDecimal remaining=g.targetAmount().subtract(g.currentAmount()).max(BigDecimal.ZERO);long months=Math.max(1,java.time.temporal.ChronoUnit.MONTHS.between(LocalDate.now().withDayOfMonth(1),g.deadline().withDayOfMonth(1)));BigDecimal pace=remaining.divide(BigDecimal.valueOf(months),2,RoundingMode.HALF_UP);b.append("- **").append(g.name()).append(":** ").append(Money.inr(g.currentAmount())).append(" of ").append(Money.inr(g.targetAmount())).append(" · ").append(Money.inr(remaining)).append(" left · about ").append(Money.inr(pace)).append("/month to target\n");}b.append("\nGoal amounts are earmarks, not extra assets, so they do not inflate or reduce net worth.");return ok(i,b,"goals,target dates,BigDecimal monthly pace");}
    private ToolResult bills(State s,FinancialIntent i){List<Bill> bills=s.bills().stream().filter(b->!b.paid()).sorted(Comparator.comparing(Bill::dueDate)).toList();if(bills.isEmpty())return missing(i,"No unpaid bills are recorded.","unpaid bills");BigDecimal total=bills.stream().map(Bill::amount).reduce(BigDecimal.ZERO,BigDecimal::add);StringBuilder b=new StringBuilder("## Upcoming bills\n**Unpaid total: ").append(Money.inr(total)).append("**\n\n");bills.stream().limit(10).forEach(x->b.append("- ").append(date(x.dueDate())).append(" · **").append(x.name()).append("** · ").append(Money.inr(x.amount())).append(x.recurring()?" · recurring":"").append('\n'));return ok(i,b,"unpaid bills ordered by due date");}
    private ToolResult investments(State s,FinancialIntent i){if(s.investments().isEmpty())return missing(i,"No investment holdings are recorded. I will not invent prices, returns, or market data.","investments/current values");BigDecimal current=s.investments().stream().map(Investment::currentValue).reduce(BigDecimal.ZERO,BigDecimal::add);StringBuilder b=new StringBuilder("## Recorded investments\n- Current recorded total: **").append(Money.inr(current)).append("**\n\n");for(Investment x:s.investments())b.append("- ").append(x.name()).append(": ").append(Money.inr(x.currentValue())).append(" · planned contribution ").append(Money.inr(x.monthlyContribution())).append('\n');b.append("\nFINORA has no live market feed or stored cost basis, so it cannot truthfully calculate returns. Values are only as current as your records.");return ok(i,b,"investment current recorded values");}
    private ToolResult affordability(State s,FinancialIntent i,String q){Optional<BigDecimal> price=extractMoney(q);if(price.isEmpty())return missing(i,"Tell me the purchase price (for example, “Can I afford ₹30,000?”). I will compare it with recorded cash, bills, debts, and monthly free cash.","purchase price");BigDecimal p=price.get(),unpaid=s.bills().stream().filter(b->!b.paid()&&!b.dueDate().isAfter(LocalDate.now().plusDays(30))).map(Bill::amount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal monthExpense=monthExpenses(s),free=s.monthlyIncome().subtract(monthExpense).subtract(s.monthlyDebtPayments());BigDecimal cashAfter=s.totalBalance().subtract(unpaid).subtract(p);String verdict=(cashAfter.signum()>=0&&free.signum()>0)?"Potentially affordable from recorded cash flow":"Not comfortably supported by the recorded numbers";String answer="## Affordability check\n**"+verdict+"**\n\n- Purchase: "+Money.inr(p)+"\n- Current account cash: "+Money.inr(s.totalBalance())+"\n- Bills due within 30 days: "+Money.inr(unpaid)+"\n- Estimated monthly free cash: "+Money.inr(free)+"\n- Cash after bills and purchase: **"+Money.inr(cashAfter)+"**\n\nThis is a scenario only and does not change your records. It does not account for unrecorded emergencies, taxes, or irregular expenses.";return ok(i,answer,"cash-bills-purchase; recurringIncome-monthExpenses-debtPayments");}
    private ToolResult forecast(State s,FinancialIntent i,String q){if(s.monthlyIncome().signum()==0&&s.transactions().isEmpty())return missing(i,"I need recurring income or transaction history to build a forecast.","income/transactions");BigDecimal expenses=monthExpenses(s),monthly=s.monthlyIncome().subtract(expenses).subtract(s.monthlyDebtPayments());int months=q!=null&&q.toLowerCase().contains("six")?6:3;BigDecimal projected=s.totalBalance().add(monthly.multiply(BigDecimal.valueOf(months)));String answer="## "+months+"-month baseline scenario\n- Starting account cash: **"+Money.inr(s.totalBalance())+"**\n- Recurring monthly income: "+Money.inr(s.monthlyIncome())+"\n- This month's recorded expenses used as baseline: "+Money.inr(expenses)+"\n- Monthly debt payments: "+Money.inr(s.monthlyDebtPayments())+"\n- Baseline monthly change: **"+Money.inr(monthly)+"**\n- Projected cash after "+months+" months: **"+Money.inr(projected)+"**\n\nAssumption: these inputs stay constant. This is not a prediction, and no real records were altered.";return ok(i,answer,"deterministic baseline scenario");}
    private ToolResult health(State s,FinancialIntent i){if(s.accounts().isEmpty()&&s.transactions().isEmpty())return missing(i,"There is not enough recorded data to assess financial health. Add an account and some income/expense history first.","accounts/transactions");BigDecimal expenses=monthExpenses(s),free=s.monthlyIncome().subtract(expenses).subtract(s.monthlyDebtPayments());String status=free.signum()>0?"Positive monthly margin":"Monthly margin needs attention";long overdue=s.bills().stream().filter(b->!b.paid()&&b.dueDate().isBefore(LocalDate.now())).count();String action;if(overdue>0)action="Review the "+overdue+" recorded overdue bill"+(overdue==1?"":"s")+" first.";else if(free.signum()<=0)action="Review the largest discretionary spending categories before adding new commitments.";else if(!s.debts().isEmpty())action="Protect this positive margin, then review the highest-rate debt and emergency reserve.";else action="Keep the positive margin protected and direct it toward your highest-priority active goal.";String answer="## Financial health check\n**"+status+"**\n\n- Net worth: "+Money.inr(s.netWorth())+"\n- Recurring income: "+Money.inr(s.monthlyIncome())+"\n- This month's spending: "+Money.inr(expenses)+"\n- Monthly debt payments: "+Money.inr(s.monthlyDebtPayments())+"\n- Estimated margin: **"+Money.inr(free)+"**\n\n### Evidence-based next action\n"+action+"\n\nThis is an evidence-based snapshot, not a credit score or regulated financial advice.";return ok(i,answer,"net worth and monthly cash-flow metrics");}
    private ToolResult plan(State s,FinancialIntent i){if(s.monthlyIncome().signum()==0)return missing(i,"Add recurring monthly income before I build a monthly allocation plan.","recurring income");BigDecimal fixed=monthExpenses(s).add(s.monthlyDebtPayments()),available=s.monthlyIncome().subtract(fixed);String answer="## Monthly plan from recorded data\n- Recurring income: **"+Money.inr(s.monthlyIncome())+"**\n- Current-month spending + debt payments: **"+Money.inr(fixed)+"**\n- Amount left to allocate: **"+Money.inr(available)+"**\n\n### Next action\n"+(available.signum()>0?"Direct this margin to urgent bills, an emergency buffer, highest-interest debt, and then active goals. Adjust the exact split to your priorities.":"The recorded baseline has no positive margin. Review discretionary categories or income before increasing goal contributions.")+"\n\nThis plan uses current records and does not move money automatically.";return ok(i,answer,"income-expenses-debtPayments");}
    private ToolResult general(State s,FinancialIntent i){return ok(i,"I can answer questions using your recorded balances, transactions, budgets, bills, debts, goals, investments, and recurring income. For example: **“Where did I spend most this month?”**, **“Can I afford ₹30,000?”**, or **“Which debt should I pay first?”**\n\nFor general education, I can explain concepts, but I will state assumptions and will not invent market data.","no financial tool required");}
    private static String payoffEstimate(Debt debt){if(debt.remainingAmount().signum()<=0)return "paid";if(debt.minimumPayment().signum()<=0)return "payoff timing needs a payment";double principal=debt.remainingAmount().doubleValue(),payment=debt.minimumPayment().doubleValue(),rate=debt.interestRate().doubleValue()/1200d;if(rate==0)return (long)Math.ceil(principal/payment)+" months at this payment";if(payment<=principal*rate)return "payment does not cover monthly interest";long months=(long)Math.ceil(-Math.log(1-rate*principal/payment)/Math.log(1+rate));return months+" months at fixed rate/payment";}
    private static BigDecimal monthExpenses(State s){return s.transactions().stream().filter(t->t.type()==TransactionRecord.TransactionType.EXPENSE&&isThisMonth(t.date())).map(TransactionRecord::amount).reduce(BigDecimal.ZERO,BigDecimal::add);}
    private static String date(LocalDate date){return date.format(java.time.format.DateTimeFormatter.ofPattern("dd MMM yyyy"));}
    private static boolean isThisMonth(LocalDate date){LocalDate n=LocalDate.now();return date.getYear()==n.getYear()&&date.getMonth()==n.getMonth();}
    private static List<BigDecimal> extractNumbers(String text){if(text==null)return List.of();List<BigDecimal> values=new ArrayList<>();Matcher m=Pattern.compile("[0-9][0-9,]*(?:\\.[0-9]+)?").matcher(text);while(m.find())try{values.add(new BigDecimal(m.group().replace(",","")));}catch(NumberFormatException ignored){}return values;}
    private static Optional<BigDecimal> extractMoney(String text){if(text==null)return Optional.empty();Matcher m=Pattern.compile("(?:₹|rs\\.?|inr|\\$)?\\s*([0-9][0-9,]*(?:\\.[0-9]{1,2})?)",Pattern.CASE_INSENSITIVE).matcher(text);while(m.find()){try{BigDecimal value=new BigDecimal(m.group(1).replace(",",""));if(value.signum()>0)return Optional.of(value);}catch(NumberFormatException ignored){}}return Optional.empty();}
    private static ToolResult ok(FinancialIntent i,CharSequence a,String trace){return new ToolResult(i,a.toString(),trace,List.of(),true);}
    private static ToolResult missing(FinancialIntent i,String a,String missing){return new ToolResult(i,a,"missing:"+missing,List.of(missing),true);}
}
