package com.finora.ai;

public enum FinancialIntent {
    BALANCE_QUERY, INCOME_QUERY, EXPENSE_QUERY, TRANSACTION_QUERY, BUDGET_QUERY, DEBT_QUERY,
    EMI_QUERY, GOAL_QUERY, INVESTMENT_QUERY, SAVINGS_QUERY, BILL_QUERY, SUBSCRIPTION_QUERY,
    NET_WORTH_QUERY, FORECAST_QUERY, AFFORDABILITY_QUERY, SCENARIO_QUERY,
    FINANCIAL_HEALTH_QUERY, MONTHLY_PLAN_QUERY, MEMORY_COMMAND, GENERAL_FINANCE_QUERY
}
