package com.finora.ui.pages;

import com.finora.brain.*;
import com.finora.model.Account;
import com.finora.model.Debt;
import com.finora.ui.Icons;
import com.finora.ui.PageContext;
import com.finora.ui.Ui;
import com.finora.util.Money;
import javafx.collections.FXCollections;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.chart.*;
import javafx.scene.control.*;
import javafx.scene.layout.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;

public final class DebtPage {
    private DebtPage(){}
    public static Node build(FinoraBrain.BrainState state,PageContext context){
        VBox content=new VBox(22);content.getStyleClass().add("page-content");Button add=Ui.button("Add debt","primary-button");add.setGraphic(Icons.create("plus",16));add.setOnAction(e->addDebt(state,context));
        content.getChildren().add(Ui.row(Ui.sectionTitle("LIABILITY CONTROL","Debt Center","Prioritize obligations, protect minimums and model the fastest responsible path to zero."),Ui.spacer(),add));
        BigDecimal minimum=state.snapshot().debts().stream().map(Debt::minimumPayment).reduce(BigDecimal.ZERO,BigDecimal::add);DebtEngine engine=new DebtEngine();DebtEngine.DebtForecast forecast=engine.forecast(state.snapshot().debts(),state.monthlyPlan().debtAndEmi());
        GridPane stats=new GridPane();stats.setHgap(14);Ui.gridColumns(stats,25,25,25,25);stats.add(stat("TOTAL DEBT",Money.inr(state.snapshot().liabilities()),state.snapshot().debts().size()+" obligations","negative"),0,0);stats.add(stat("MONTHLY MINIMUMS",Money.inr(minimum),"recorded commitments","neutral"),1,0);stats.add(stat("PLAN PAYMENT",Money.inr(state.monthlyPlan().debtAndEmi()),"recommended capacity","positive"),2,0);stats.add(stat("DEBT-FREE",forecast.debtFreeMonth()==null?"Needs plan":forecast.debtFreeMonth().format(DateTimeFormatter.ofPattern("MMM yyyy")),forecast.months()<0?"—":forecast.months()+" months estimated","positive"),3,0);content.getChildren().add(stats);
        TabPane tabs=new TabPane();tabs.getStyleClass().add("finora-tabs");tabs.setTabClosingPolicy(TabPane.TabClosingPolicy.UNAVAILABLE);tabs.getTabs().add(new Tab("Priority plan",priorityTab(state,context,engine)));tabs.getTabs().add(new Tab("Payoff forecast",forecastTab(state,forecast)));tabs.getTabs().add(new Tab("EMI lab",emiTab()));content.getChildren().add(tabs);return Ui.scroll(content);
    }
    private static Node priorityTab(FinoraBrain.BrainState state,PageContext context,DebtEngine engine){
        VBox root=new VBox(18);root.setPadding(new javafx.geometry.Insets(20,0,0,0));DebtEngine.StrategyAdvice advice=engine.recommendStrategy(state.snapshot().debts(),LocalDate.now());
        ToggleGroup strategies=new ToggleGroup();HBox choices=new HBox(8);for(DebtEngine.Strategy s:DebtEngine.Strategy.values()){ToggleButton b=new ToggleButton(title(s));b.setToggleGroup(strategies);b.setUserData(s);b.getStyleClass().add("strategy-toggle");if(s==advice.strategy())b.setSelected(true);choices.getChildren().add(b);}Region spacer=Ui.spacer();HBox strategyRow=Ui.row(choices,spacer,Ui.label("RECOMMENDED  "+title(advice.strategy()).toUpperCase(),"recommended-chip"));
        Label explanation=Ui.label(advice.explanation(),"body-copy");explanation.setWrapText(true);VBox strategyCard=Ui.card(Ui.label("PAYMENT STRATEGY","eyebrow"),strategyRow,explanation);root.getChildren().add(strategyCard);
        VBox list=new VBox(10);Runnable render=()->{list.getChildren().clear();Toggle selected=(Toggle)strategies.getSelectedToggle();DebtEngine.Strategy strategy=selected==null?advice.strategy():(DebtEngine.Strategy)selected.getUserData();List<DebtEngine.PrioritizedDebt> ranked=engine.prioritize(state.snapshot().debts(),strategy,LocalDate.now());if(ranked.isEmpty())list.getChildren().add(Ui.card(Ui.label("You have no active debt records.","empty-copy")));for(int i=0;i<ranked.size();i++)list.getChildren().add(debtRow(i+1,ranked.get(i),state,context));};strategies.selectedToggleProperty().addListener((o,a,b)->render.run());render.run();root.getChildren().addAll(Ui.label("PRIORITY QUEUE","eyebrow"),list);return root;
    }
    private static Node debtRow(int rank,DebtEngine.PrioritizedDebt item,FinoraBrain.BrainState state,PageContext context){Debt d=item.debt();long days=d.dueDate()==null?999:ChronoUnit.DAYS.between(LocalDate.now(),d.dueDate());String tone=days<0?"critical":days<=7?"warning":days<=30?"attention":"healthy";Label number=Ui.label(String.format("%02d",rank),"rank-number");VBox rankBox=new VBox(number,Ui.label(tone.toUpperCase(),"micro-label"));rankBox.setAlignment(Pos.CENTER);rankBox.getStyleClass().add("rank-box");
        Label name=Ui.label(d.name(),"debt-name");Label meta=Ui.label(d.type().name().replace('_',' ') + "  ·  "+d.interestRate().stripTrailingZeros().toPlainString()+"% p.a.","muted");VBox identity=new VBox(4,name,meta);HBox.setHgrow(identity,Priority.ALWAYS);
        ProgressBar progress=new ProgressBar(d.originalAmount().signum()==0?0:d.originalAmount().subtract(d.remainingAmount()).divide(d.originalAmount(),4,java.math.RoundingMode.HALF_UP).doubleValue());progress.setPrefWidth(150);progress.getStyleClass().add("debt-progress");VBox paid=new VBox(4,Ui.label("REPAID","micro-label"),progress);Label due=Ui.label(d.dueDate()==null?"No due date":days<0?Math.abs(days)+" days overdue":days+" days","due-"+tone);VBox amount=new VBox(3,Ui.label(Money.inr(d.remainingAmount()),"debt-amount"),Ui.label("Min "+Money.inr(d.minimumPayment()),"micro-copy"));amount.setAlignment(Pos.CENTER_RIGHT);
        Button pay=Ui.button("Record payment","secondary-button");pay.setOnAction(e->payDebt(d,state,context));VBox reason=new VBox(3,Ui.label(item.reason(),"micro-copy"),due);HBox top=Ui.row(rankBox,identity,paid,amount,pay);VBox card=Ui.card(top,reason);card.getStyleClass().add("debt-row");return card;}
    private static Node forecastTab(FinoraBrain.BrainState state,DebtEngine.DebtForecast forecast){VBox root=new VBox(18);root.setPadding(new javafx.geometry.Insets(20,0,0,0));CategoryAxis x=new CategoryAxis();NumberAxis y=new NumberAxis();y.setTickLabelsVisible(false);LineChart<String,Number> chart=new LineChart<>(x,y);chart.setLegendVisible(false);chart.setCreateSymbols(false);chart.setAnimated(false);chart.getStyleClass().add("debt-chart");XYChart.Series<String,Number> series=new XYChart.Series<>();int step=Math.max(1,forecast.balances().size()/8);for(int i=0;i<forecast.balances().size();i+=step)series.getData().add(new XYChart.Data<>(i==0?"Now":"M"+i,forecast.balances().get(i)));if(!forecast.balances().isEmpty()&&(forecast.balances().size()-1)%step!=0)series.getData().add(new XYChart.Data<>("M"+(forecast.balances().size()-1),forecast.balances().getLast()));chart.getData().add(series);
        GridPane details=new GridPane();details.setHgap(12);Ui.gridColumns(details,33,33,34);details.add(stat("ESTIMATED INTEREST",Money.inr(forecast.estimatedInterest()),"rates held constant","neutral"),0,0);details.add(stat("TOTAL PAID",Money.inr(forecast.totalPaid()),"principal + interest","neutral"),1,0);details.add(stat("PAYMENT ASSUMPTION",Money.inr(state.monthlyPlan().debtAndEmi()),"every month","positive"),2,0);root.getChildren().addAll(Ui.card(Ui.label("DEBT DECLINE FORECAST","eyebrow"),Ui.label("Your path to zero","section-title"),chart),details,assumption("This forecast assumes all recorded rates and the plan payment remain constant. Penalties and unrecorded fees are excluded."));return root;}
    private static Node emiTab(){
        EMIEngine engine=new EMIEngine();VBox root=new VBox(18);root.setPadding(new javafx.geometry.Insets(20,0,0,0));
        TextField principal=new TextField();principal.setPromptText("Enter loan amount");TextField rate=new TextField();rate.setPromptText("Annual rate");TextField months=new TextField();months.setPromptText("Months");
        Label emi=Ui.label("—","safe-value");Label totalInterest=Ui.label("—","stat-value");Label repayment=Ui.label("—","stat-value");
        Button calculate=Ui.button("Calculate EMI","primary-button");
        calculate.setOnAction(e->{try{EMIEngine.EMIResult r=engine.calculate(decimal(principal),decimal(rate),Integer.parseInt(months.getText()));emi.setText(Money.inr(r.emi()));totalInterest.setText(Money.inr(r.totalInterest()));repayment.setText(Money.inr(r.totalRepayment()));}catch(Exception ex){emi.setText("Check inputs");}});
        GridPane form=new GridPane();form.setHgap(12);Ui.gridColumns(form,28,28,28,16);form.add(field("LOAN AMOUNT",principal),0,0);form.add(field("ANNUAL RATE %",rate),1,0);form.add(field("TENURE (MONTHS)",months),2,0);form.add(calculate,3,0);
        GridPane outputs=new GridPane();outputs.setHgap(12);Ui.gridColumns(outputs,33,33,34);
        VBox emiBox=stat("MONTHLY EMI","—","calculated payment","positive");((Label)emiBox.getChildren().get(1)).textProperty().bind(emi.textProperty());outputs.add(emiBox,0,0);
        VBox intBox=stat("TOTAL INTEREST","—","over full tenure","neutral");((Label)intBox.getChildren().get(1)).textProperty().bind(totalInterest.textProperty());outputs.add(intBox,1,0);
        VBox repBox=stat("TOTAL REPAYMENT","—","principal + interest","neutral");((Label)repBox.getChildren().get(1)).textProperty().bind(repayment.textProperty());outputs.add(repBox,2,0);
        TextField extra=new TextField();extra.setPromptText("Enter extra amount");Button compare=Ui.button("Compare prepayment","secondary-button");
        Label tenureResult=Ui.label("Enter an extra payment to compare options.","body-copy");tenureResult.setWrapText(true);Label emiResult=Ui.label("","body-copy");emiResult.setWrapText(true);
        compare.setOnAction(e->{try{BigDecimal p=decimal(principal),r=decimal(rate),x=decimal(extra);int m=Integer.parseInt(months.getText());EMIEngine.EMIResult base=engine.calculate(p,r,m);EMIEngine.PrepaymentResult tenure=engine.prepay(p,r,m,base.emi(),x,true);EMIEngine.PrepaymentResult lowerEmi=engine.prepay(p,r,m,base.emi(),x,false);tenureResult.setText("REDUCE TENURE  ·  Finish "+tenure.monthsReduced()+" months sooner · estimated interest saved "+Money.inr(tenure.interestSaved()));emiResult.setText("REDUCE EMI  ·  New EMI "+Money.inr(lowerEmi.newEmi())+" · tenure unchanged · estimated interest saved "+Money.inr(lowerEmi.interestSaved()));}catch(Exception ex){tenureResult.setText("Check the prepayment inputs: "+ex.getMessage());emiResult.setText("");}});
        HBox prepayForm=Ui.row(field("EXTRA PAYMENT",extra),compare);VBox prepay=Ui.card(Ui.label("PREPAYMENT SIMULATOR","eyebrow"),Ui.label("Reduce tenure or reduce EMI","section-title"),prepayForm,tenureResult,emiResult);
        root.getChildren().addAll(Ui.card(Ui.label("STANDALONE EMI CALCULATOR","eyebrow"),Ui.label("Model a fixed-rate reducing-balance loan","section-title"),form),outputs,prepay,assumption("Calculations use the standard reducing-balance EMI formula. Actual lender schedules can differ due to fees, daily accrual and rounding."));return root;
    }
    private static VBox field(String label,Control input){input.setMaxWidth(Double.MAX_VALUE);return new VBox(7,Ui.label(label,"field-label"),input);}
    private static VBox assumption(String text){Label body=Ui.label(text,"body-copy");body.setWrapText(true);VBox box=Ui.card(Ui.label("ASSUMPTION","assumption-label"),body);box.getStyleClass().add("assumption-card");return box;}
    private static VBox stat(String title,String value,String sub,String tone){VBox b=Ui.card(Ui.label(title,"eyebrow"),Ui.label(value,"stat-value",tone),Ui.label(sub,"stat-detail"));b.getStyleClass().add("summary-card");return b;}
    private static String title(DebtEngine.Strategy s){return switch(s){case AVALANCHE->"Avalanche";case SNOWBALL->"Snowball";case URGENCY->"Urgency";case HYBRID->"Hybrid";case PERSONAL_PRIORITY->"Personal";};}
    private static void payDebt(Debt debt,FinoraBrain.BrainState state,PageContext ctx){Dialog<ButtonType> d=new Dialog<>();d.setTitle("Record debt payment");d.initOwner(ctx.owner().get());ButtonType save=new ButtonType("Record payment",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,save);TextField amount=new TextField(debt.minimumPayment().min(debt.remainingAmount()).toPlainString());ComboBox<Account> account=accountBox(state);VBox body=new VBox(12,Ui.label("DEBT PAYMENT","eyebrow"),Ui.label(debt.name(),"dialog-title"),Ui.label("Remaining "+Money.inr(debt.remainingAmount()),"muted"),field("PAYMENT AMOUNT",amount),field("FROM ACCOUNT",account));d.getDialogPane().setContent(body);Node button=d.getDialogPane().lookupButton(save);button.addEventFilter(javafx.event.ActionEvent.ACTION,e->{try{BigDecimal value=new BigDecimal(amount.getText().replace(",",""));if(value.compareTo(debt.remainingAmount())>0)throw new IllegalArgumentException("Payment cannot exceed the remaining debt.");ctx.controller().execute(()->ctx.controller().finance().recordDebtPayment(debt.id(),account.getValue().id(),value,debt.name()),()->{ctx.toast().accept("Debt payment recorded");ctx.refresh().run();},ctx.error());}catch(Exception ex){e.consume();validation(ex.getMessage());}});d.showAndWait();}
    private static void addDebt(FinoraBrain.BrainState state,PageContext ctx){Dialog<ButtonType>d=new Dialog<>();d.setTitle("Add debt");d.initOwner(ctx.owner().get());ButtonType save=new ButtonType("Add debt",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,save);TextField name=new TextField();TextField original=new TextField();TextField remaining=new TextField();TextField rate=new TextField("0");TextField minimum=new TextField();ComboBox<Debt.DebtType> type=new ComboBox<>(FXCollections.observableArrayList(Debt.DebtType.values()));type.getSelectionModel().select(Debt.DebtType.PERSONAL);DatePicker due=new DatePicker(LocalDate.now().plusMonths(1));ComboBox<Integer> priority=new ComboBox<>(FXCollections.observableArrayList(1,2,3,4,5));priority.getSelectionModel().select(Integer.valueOf(3));CheckBox penalty=new CheckBox("Missed payment has a financial consequence");VBox form=new VBox(10,field("PERSON / INSTITUTION",name),Ui.row(field("ORIGINAL AMOUNT",original),field("REMAINING AMOUNT",remaining)),Ui.row(field("INTEREST RATE %",rate),field("MINIMUM PAYMENT",minimum)),Ui.row(field("DEBT TYPE",type),field("NEXT DUE DATE",due)),field("MANUAL PRIORITY (1 = HIGHEST)",priority),penalty);d.getDialogPane().setContent(new VBox(10,Ui.label("NEW LIABILITY","eyebrow"),Ui.label("Add debt","dialog-title"),form));d.getDialogPane().lookupButton(save).addEventFilter(javafx.event.ActionEvent.ACTION,e->{try{BigDecimal o=decimal(original),r=remaining.getText().isBlank()?o:decimal(remaining);Debt debt=new Debt(0,name.getText(),type.getValue(),o,r,decimal(rate),decimal(minimum),due.getValue(),priority.getValue(),3,penalty.isSelected(),"",java.time.Instant.now(),java.time.Instant.now());ctx.controller().execute(()->ctx.controller().finance().addDebt(debt),()->{ctx.toast().accept("Debt added");ctx.refresh().run();},ctx.error());}catch(Exception ex){e.consume();validation(ex.getMessage());}});d.showAndWait();}
    private static BigDecimal decimal(TextField f){return new BigDecimal(f.getText().replace(",","").trim());}
    private static ComboBox<Account> accountBox(FinoraBrain.BrainState s){ComboBox<Account>b=new ComboBox<>(FXCollections.observableArrayList(s.snapshot().accounts()));b.setCellFactory(c->new ListCell<>(){@Override protected void updateItem(Account a,boolean empty){super.updateItem(a,empty);setText(empty||a==null?null:a.name()+" · "+Money.inr(a.balance()));}});b.setButtonCell(new ListCell<>(){@Override protected void updateItem(Account a,boolean empty){super.updateItem(a,empty);setText(empty||a==null?null:a.name()+" · "+Money.inr(a.balance()));}});b.getSelectionModel().selectFirst();return b;}
    private static void validation(String text){new Alert(Alert.AlertType.WARNING,text,ButtonType.OK).showAndWait();}
}
