package com.finora.ui.pages;

import com.finora.brain.FinoraBrain;
import com.finora.brain.GoalEngine;
import com.finora.model.Account;
import com.finora.model.Goal;
import com.finora.ui.Icons;
import com.finora.ui.PageContext;
import com.finora.ui.Ui;
import com.finora.util.Money;
import javafx.collections.FXCollections;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public final class GoalsPage {
    private GoalsPage(){}
    public static Node build(FinoraBrain.BrainState state,PageContext ctx){VBox content=new VBox(22);content.getStyleClass().add("page-content");Button add=Ui.button("New goal","primary-button");add.setGraphic(Icons.create("plus",16));add.setOnAction(e->addGoal(ctx));content.getChildren().add(Ui.row(Ui.sectionTitle("PURPOSEFUL SAVING","Goals","Fund critical outcomes first, then optimize deadlines and monthly contributions."),Ui.spacer(),add));
        BigDecimal target=state.snapshot().goals().stream().map(Goal::targetAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal current=state.snapshot().goals().stream().map(Goal::currentAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal monthly=state.snapshot().goals().stream().map(Goal::monthlyContribution).reduce(BigDecimal.ZERO,BigDecimal::add);GridPane stats=new GridPane();stats.setHgap(14);Ui.gridColumns(stats,33,33,34);stats.add(stat("TOTAL TARGET",Money.inr(target),state.snapshot().goals().size()+" active goals"),0,0);stats.add(stat("CURRENTLY FUNDED",Money.inr(current),target.signum()==0?"0%":current.multiply(new BigDecimal("100")).divide(target,0,RoundingMode.DOWN)+"% complete"),1,0);stats.add(stat("MONTHLY CONTRIBUTION",Money.inr(monthly),"configured pace"),2,0);content.getChildren().add(stats);
        GoalEngine engine=new GoalEngine();VBox list=new VBox(12);for(Goal g:engine.prioritize(state.snapshot().goals()))list.getChildren().add(goalCard(g,engine.forecast(g,g.monthlyContribution()),state,ctx));if(list.getChildren().isEmpty())list.getChildren().add(Ui.card(Ui.label("Add a goal to begin forecasting.","empty-copy")));content.getChildren().add(list);return Ui.scroll(content);}
    private static VBox goalCard(Goal g,GoalEngine.GoalForecast f,FinoraBrain.BrainState state,PageContext ctx){double progress=g.currentAmount().divide(g.targetAmount(),6,RoundingMode.HALF_UP).doubleValue();StackPane badge=new StackPane(Ui.label(g.priority().name().substring(0,1),"goal-letter"));badge.getStyleClass().addAll("goal-badge","goal-"+g.priority().name().toLowerCase());VBox identity=new VBox(4,Ui.label(g.name(),"debt-name"),Ui.label(g.priority().name()+" PRIORITY · "+(g.deadline()==null?"No deadline":g.deadline().format(DateTimeFormatter.ofPattern("dd MMM yyyy"))),"muted"));HBox.setHgrow(identity,Priority.ALWAYS);VBox amount=new VBox(3,Ui.label(Money.inr(g.currentAmount()),"debt-amount"),Ui.label("of "+Money.inr(g.targetAmount()),"micro-copy"));amount.setAlignment(Pos.CENTER_RIGHT);Button contribute=Ui.button("Add contribution","secondary-button");contribute.setOnAction(e->contribute(g,state,ctx));ProgressBar bar=new ProgressBar(progress);bar.setMaxWidth(Double.MAX_VALUE);bar.getStyleClass().add("goal-progress");Label forecast=Ui.label(f.estimatedCompletion()==null?"Contribution needed":"Estimated completion · "+f.estimatedCompletion().format(DateTimeFormatter.ofPattern("MMMM yyyy")),f.onTrack()?"due-healthy":"due-warning");HBox metrics=Ui.row(Ui.label(Math.round(progress*100)+"% funded","micro-copy"),Ui.spacer(),Ui.label(Money.inr(g.monthlyContribution())+" / month","micro-copy"),forecast);return Ui.card(Ui.row(badge,identity,amount,contribute),bar,metrics);}
    private static VBox stat(String title,String value,String sub){VBox b=Ui.card(Ui.label(title,"eyebrow"),Ui.label(value,"stat-value"),Ui.label(sub,"stat-detail"));b.getStyleClass().add("summary-card");return b;}
    private static void contribute(Goal g,FinoraBrain.BrainState state,PageContext ctx){Dialog<ButtonType>d=new Dialog<>();d.setTitle("Goal contribution");d.initOwner(ctx.owner().get());ButtonType save=new ButtonType("Add contribution",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,save);TextField amount=new TextField(g.monthlyContribution().toPlainString());ComboBox<Account> account=accountBox(state);d.getDialogPane().setContent(new VBox(12,Ui.label("GOAL CONTRIBUTION","eyebrow"),Ui.label(g.name(),"dialog-title"),Ui.label("Remaining "+Money.inr(g.remaining()),"muted"),field("AMOUNT",amount),field("FROM ACCOUNT",account)));d.getDialogPane().lookupButton(save).addEventFilter(javafx.event.ActionEvent.ACTION,e->{try{BigDecimal value=new BigDecimal(amount.getText().replace(",",""));if(value.compareTo(g.remaining())>0)throw new IllegalArgumentException("Contribution exceeds the remaining goal amount.");ctx.controller().execute(()->ctx.controller().finance().contributeToGoal(g.id(),account.getValue().id(),value,g.name()),()->{ctx.toast().accept(value.compareTo(g.remaining())==0?"Goal completed 🎯":"Goal contribution recorded");ctx.refresh().run();},ctx.error());}catch(Exception ex){e.consume();new Alert(Alert.AlertType.WARNING,ex.getMessage(),ButtonType.OK).showAndWait();}});d.showAndWait();}
    private static void addGoal(PageContext ctx){Dialog<ButtonType>d=new Dialog<>();d.setTitle("New goal");d.initOwner(ctx.owner().get());ButtonType save=new ButtonType("Create goal",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,save);TextField name=new TextField();TextField target=new TextField();TextField current=new TextField("0");TextField monthly=new TextField();DatePicker deadline=new DatePicker(LocalDate.now().plusMonths(12));ComboBox<Goal.Priority> priority=new ComboBox<>(FXCollections.observableArrayList(Goal.Priority.values()));priority.getSelectionModel().select(Goal.Priority.MEDIUM);d.getDialogPane().setContent(new VBox(10,Ui.label("NEW SAVINGS GOAL","eyebrow"),Ui.label("Create goal","dialog-title"),field("GOAL NAME",name),Ui.row(field("TARGET AMOUNT",target),field("CURRENT AMOUNT",current)),Ui.row(field("MONTHLY CONTRIBUTION",monthly),field("DEADLINE",deadline)),field("PRIORITY",priority)));d.getDialogPane().lookupButton(save).addEventFilter(javafx.event.ActionEvent.ACTION,e->{try{Goal goal=new Goal(0,name.getText(),decimal(target),decimal(current),decimal(monthly),deadline.getValue(),priority.getValue(),"",Instant.now(),Instant.now());ctx.controller().execute(()->ctx.controller().finance().addGoal(goal),()->{ctx.toast().accept("Goal created");ctx.refresh().run();},ctx.error());}catch(Exception ex){e.consume();new Alert(Alert.AlertType.WARNING,ex.getMessage(),ButtonType.OK).showAndWait();}});d.showAndWait();}
    private static BigDecimal decimal(TextField field){return new BigDecimal(field.getText().replace(",","").trim());}
    private static VBox field(String label,Control input){input.setMaxWidth(Double.MAX_VALUE);HBox.setHgrow(input,Priority.ALWAYS);VBox box=new VBox(7,Ui.label(label,"field-label"),input);HBox.setHgrow(box,Priority.ALWAYS);return box;}
    private static ComboBox<Account> accountBox(FinoraBrain.BrainState s){ComboBox<Account>b=new ComboBox<>(FXCollections.observableArrayList(s.snapshot().accounts()));b.setCellFactory(c->cell());b.setButtonCell(cell());b.getSelectionModel().selectFirst();return b;}
    private static ListCell<Account> cell(){return new ListCell<>(){@Override protected void updateItem(Account a,boolean empty){super.updateItem(a,empty);setText(empty||a==null?null:a.name()+" · "+Money.inr(a.balance()));}};}
}
