package com.finora.ui.pages;

import com.finora.brain.FinoraBrain;
import com.finora.brain.MonthlyPlan;
import com.finora.brain.SafeToSpendResult;
import com.finora.model.Budget;
import com.finora.ui.Ui;
import com.finora.util.Money;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.LinkedHashMap;
import java.util.Map;

public final class PlanPage {
    private PlanPage(){}
    public static Node build(FinoraBrain.BrainState state,Runnable openIncome){MonthlyPlan plan=state.monthlyPlan();VBox content=new VBox(22);content.getStyleClass().add("page-content");Button income=Ui.button(state.snapshot().expectedRecurringIncome().signum()==0?"Add monthly income":"Manage income","secondary-button");income.setOnAction(event->openIncome.run());content.getChildren().add(Ui.row(Ui.sectionTitle("MONTHLY CONTROL SYSTEM","Financial Plan","A priority-based allocation built from your records — not a generic percentage rule."),Ui.spacer(),Ui.label("AUTO-CALCULATED","recommended-chip"),income));
        GridPane top=new GridPane();top.setHgap(18);Ui.gridColumns(top,68,32);top.add(allocationCard(plan),0,0);top.add(scoreCard(plan),1,0);content.getChildren().add(top);
        GridPane middle=new GridPane();middle.setHgap(18);Ui.gridColumns(middle,42,58);middle.add(safeCard(state.safeToSpend()),0,0);middle.add(scenarioCard(state),1,0);content.getChildren().add(middle);
        GridPane readiness=new GridPane();readiness.setHgap(18);Ui.gridColumns(readiness,50,50);readiness.add(emergencyCard(state),0,0);readiness.add(investmentCard(state),1,0);content.getChildren().addAll(readiness,budgetCard(state));return Ui.scroll(content);}
    private static VBox allocationCard(MonthlyPlan p){VBox rows=new VBox(14);Map<String,BigDecimal> values=new LinkedHashMap<>();values.put("Essential expenses",p.essentials());values.put("Debt & EMI",p.debtAndEmi());values.put("Emergency savings",p.emergencySavings());values.put("Goals",p.goals());values.put("Long-term allocation",p.investments());values.put("Flexible spending",p.flexible());values.put("Cash reserve",p.reserve());String[] tones={"essential","debt","emergency","goal","investment","flexible","reserve"};int i=0;for(var e:values.entrySet())rows.getChildren().add(allocationRow(e.getKey(),e.getValue(),p.income(),tones[i++]));HBox header=Ui.row(new VBox(4,Ui.label("SUGGESTED ALLOCATION","eyebrow"),Ui.label(Money.inr(p.income())+" income plan","section-title")),Ui.spacer(),Ui.label("100% ASSIGNED","soft-chip"));VBox card=Ui.card(header,rows);return card;}
    private static HBox allocationRow(String name,BigDecimal value,BigDecimal income,String tone){StackPane dot=new StackPane();dot.setMinSize(9,9);dot.setMaxSize(9,9);dot.getStyleClass().addAll("allocation-dot","allocation-"+tone);Label label=Ui.label(name,"allocation-name");label.setMinWidth(155);ProgressBar bar=new ProgressBar(income.signum()==0?0:value.divide(income,6,RoundingMode.HALF_UP).doubleValue());bar.setMaxWidth(Double.MAX_VALUE);bar.getStyleClass().addAll("allocation-bar","bar-"+tone);HBox.setHgrow(bar,Priority.ALWAYS);Label valueLabel=Ui.label(Money.inr(value),"allocation-value");valueLabel.setMinWidth(100);valueLabel.setAlignment(Pos.CENTER_RIGHT);return Ui.row(dot,label,bar,valueLabel);}
    private static VBox scoreCard(MonthlyPlan p){ProgressIndicator ring=new ProgressIndicator(p.score()/100d);ring.setMinSize(118,118);ring.setMaxSize(118,118);ring.getStyleClass().add("plan-ring");Label n=Ui.label(String.valueOf(p.score()),"health-number-dark");StackPane visual=new StackPane(ring,n);VBox notes=new VBox(10);for(String text:p.explanations()){Label l=Ui.label(text,"micro-copy");l.setWrapText(true);notes.getChildren().add(Ui.row(Ui.severityDot(text.startsWith("Investment allocation is paused")?"attention":"healthy"),l));}VBox card=Ui.card(Ui.label("PLAN HEALTH","eyebrow"),visual,Ui.label(p.score()>=80?"Strong allocation":"Review allocation","score-status"),new Separator(),notes);card.setAlignment(Pos.CENTER);return card;}
    private static VBox safeCard(SafeToSpendResult s){Label value=Ui.label(Money.inr(s.today()),"safe-value");ProgressBar p=new ProgressBar(s.operatingCapacity().signum()==0?0:s.flexibleRemaining().divide(s.operatingCapacity(),4,RoundingMode.HALF_UP).doubleValue());p.setMaxWidth(Double.MAX_VALUE);p.getStyleClass().add("safe-progress");Label body=Ui.label(s.explanation(),"body-copy");body.setWrapText(true);return Ui.card(Ui.label("DAILY CONTROL","eyebrow"),Ui.label("Safe to spend","section-title"),value,Ui.label("today · "+s.remainingDays()+" days left","muted"),p,body);}
    private static VBox scenarioCard(FinoraBrain.BrainState state){Slider slider=new Slider(-30,30,-20);slider.setShowTickLabels(true);slider.setMajorTickUnit(10);Label change=Ui.label("−20% income","scenario-change");Label result=Ui.label("","scenario-result");Label detail=Ui.label("","body-copy");detail.setWrapText(true);Runnable update=()->{double percent=slider.getValue();change.setText((percent>=0?"+":"−")+Math.abs(Math.round(percent))+"% income");BigDecimal delta=state.snapshot().monthlyIncome().multiply(BigDecimal.valueOf(percent/100d));BigDecimal revised=state.snapshot().monthlyIncome().add(delta);BigDecimal baseline=state.monthlyPlan().flexible().add(state.monthlyPlan().reserve());BigDecimal gap=delta.signum()<0?delta.abs().subtract(baseline).max(BigDecimal.ZERO):BigDecimal.ZERO;result.setText(Money.inr(revised)+" / month");detail.setText(gap.signum()>0?"Flexible capacity is exhausted and the plan would be short by "+Money.inr(gap)+". Review goals and obligation timing.":"The scenario remains inside current flexible capacity and reserve. Real data is unchanged.");};slider.valueProperty().addListener((o,a,b)->update.run());update.run();VBox card=Ui.card(Ui.row(new VBox(4,Ui.label("WHAT IF?","eyebrow"),Ui.label("Income change simulator","section-title")),Ui.spacer(),change),slider,result,detail,Ui.label("SCENARIO ONLY · DOES NOT MODIFY RECORDS","assumption-label"));return card;}
    private static VBox emergencyCard(FinoraBrain.BrainState state){
        var plan=new com.finora.brain.EmergencyFundEngine().calculate(state.snapshot().essentialExpenses(),state.snapshot().emergencyFund(),com.finora.brain.EmergencyFundEngine.IncomeStability.VARIABLE);ProgressBar progress=new ProgressBar(plan.progress());progress.setMaxWidth(Double.MAX_VALUE);progress.getStyleClass().add("goal-progress");Label rationale=Ui.label(plan.rationale(),"body-copy");rationale.setWrapText(true);return Ui.card(Ui.label("EMERGENCY READINESS","eyebrow"),Ui.label(String.format("%.1f months covered",plan.monthsCovered()),"section-title"),Ui.row(Ui.label(Money.inr(plan.current()),"mini-value"),Ui.spacer(),Ui.label("Target "+Money.inr(plan.recommendedTarget()),"micro-copy")),progress,rationale);
    }
    private static VBox investmentCard(FinoraBrain.BrainState state){
        var result=new com.finora.brain.InvestmentEngine().plan(state.snapshot(),state.monthlyPlan().investments());VBox rows=new VBox(6);if(!result.eligible())rows.getChildren().add(Ui.label("Long-term allocation is paused until reserve and debt conditions are ready.","body-copy"));for(var a:result.allocations())rows.getChildren().add(Ui.row(Ui.severityDot("healthy"),Ui.label(a.category(),"priority-title"),Ui.spacer(),Ui.label(Money.inr(a.amount()),"allocation-value")));Label note=Ui.label(result.assumptions().getFirst(),"assumption-label");note.setWrapText(true);return Ui.card(Ui.label("EDUCATIONAL ALLOCATION","eyebrow"),Ui.label(result.eligible()?"Investment capacity":"Priority gate active","section-title"),rows,note);
    }
    private static VBox budgetCard(FinoraBrain.BrainState state){VBox rows=new VBox(0);if(state.snapshot().budgets().isEmpty())rows.getChildren().add(Ui.label("No category budgets are configured for this month.","empty-copy"));for(Budget b:state.snapshot().budgets()){BigDecimal spent=state.snapshot().expenseByCategory().getOrDefault(b.category(),BigDecimal.ZERO);double ratio=spent.divide(b.limitAmount(),6,RoundingMode.HALF_UP).doubleValue();ProgressBar p=new ProgressBar(Math.min(1,ratio));p.setPrefWidth(230);p.getStyleClass().add(ratio>1?"budget-over":"budget-ok");Label status=Ui.label(ratio>1?Money.inr(spent.subtract(b.limitAmount()))+" over":Money.inr(b.limitAmount().subtract(spent))+" left",ratio>1?"due-critical":"due-healthy");HBox row=Ui.row(new VBox(3,Ui.label(b.category(),"priority-title"),Ui.label(Money.inr(spent)+" of "+Money.inr(b.limitAmount()),"micro-copy")),Ui.spacer(),p,status);row.getStyleClass().add("priority-row");rows.getChildren().add(row);}return Ui.card(Ui.row(new VBox(4,Ui.label("CATEGORY BUDGETS","eyebrow"),Ui.label("Budget adherence","section-title")),Ui.spacer(),Ui.label(state.health().factors().getOrDefault("Budget",0)+" / 100","soft-chip")),rows);}
}
