package com.finora.ui.pages;

import com.finora.brain.FinoraBrain;
import com.finora.database.*;
import com.finora.model.Account;
import com.finora.ui.Icons;
import com.finora.ui.PageContext;
import com.finora.ui.Ui;
import com.finora.util.Money;
import com.finora.util.AppPaths;
import javafx.collections.FXCollections;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;

import java.math.BigDecimal;
import java.nio.file.Path;

public final class SettingsPage {
    private SettingsPage(){}
    public static Node build(FinoraBrain.BrainState state,PageContext ctx,Runnable toggleTheme,boolean dark){VBox content=new VBox(22);content.getStyleClass().add("page-content");content.getChildren().add(Ui.sectionTitle("SYSTEM CONTROL","Settings","Manage accounts, local data, optional MySQL, backups and the visual theme."));TabPane tabs=new TabPane();tabs.getStyleClass().add("finora-tabs");tabs.setTabClosingPolicy(TabPane.TabClosingPolicy.UNAVAILABLE);tabs.getTabs().add(new Tab("Workspace",workspace(state,ctx,toggleTheme,dark)));tabs.getTabs().add(new Tab("Accounts",accounts(state,ctx)));tabs.getTabs().add(new Tab("Backup & security",security(ctx)));if(state.snapshot().accounts().isEmpty())tabs.getSelectionModel().select(1);content.getChildren().add(tabs);return Ui.scroll(content);}
    private static Node workspace(FinoraBrain.BrainState state,PageContext ctx,Runnable toggleTheme,boolean dark){VBox root=new VBox(16);root.setPadding(new javafx.geometry.Insets(20,0,0,0));ToggleButton local=databaseChoice("Local H2","Private, embedded and fully offline",ctx.controller().database().type()==DatabaseType.H2);ToggleButton mysql=databaseChoice("MySQL","Optional centralized storage",ctx.controller().database().type()==DatabaseType.MYSQL);ToggleGroup group=new ToggleGroup();local.setToggleGroup(group);mysql.setToggleGroup(group);local.setOnAction(e->{if(ctx.controller().database().type()==DatabaseType.H2)return;ctx.controller().execute(()->ctx.controller().database().use(new H2ConnectionProvider(AppPaths.dataDirectory())),()->{ctx.toast().accept("Connected to local H2");ctx.refresh().run();},ctx.error());});mysql.setOnAction(e->{if(ctx.controller().database().type()!=DatabaseType.MYSQL)connectMySql(ctx);});HBox choices=new HBox(12,local,mysql);HBox.setHgrow(local,Priority.ALWAYS);HBox.setHgrow(mysql,Priority.ALWAYS);
        Button theme=Ui.button(dark?"Use light theme":"Use dark theme","secondary-button");theme.setOnAction(e->toggleTheme.run());HBox themeRow=Ui.row(new VBox(4,Ui.label("APPEARANCE","field-label"),Ui.label(dark?"Midnight theme active":"Daylight theme active","priority-title")),Ui.spacer(),theme);
        VBox connection=Ui.card(Ui.row(new VBox(4,Ui.label("DATABASE","eyebrow"),Ui.label("Storage mode","section-title")),Ui.spacer(),Ui.label("●  "+ctx.controller().database().type().name(),"offline-chip")),choices,Ui.label("MySQL credentials are accepted only in the connection dialog, kept in memory for the session and never written to logs.","body-copy"));return new VBox(16,connection,Ui.card(themeRow),disclaimer());}
    private static ToggleButton databaseChoice(String title,String copy,boolean selected){Label heading=Ui.label(title,"priority-title");Label body=Ui.label(copy,"micro-copy");body.setWrapText(true);ToggleButton b=new ToggleButton();b.setGraphic(new VBox(5,heading,body));b.setSelected(selected);b.getStyleClass().add("database-choice");b.setMaxWidth(Double.MAX_VALUE);return b;}
    private static Node accounts(FinoraBrain.BrainState state,PageContext ctx){VBox root=new VBox(16);root.setPadding(new javafx.geometry.Insets(20,0,0,0));Button add=Ui.button("Add account","primary-button");add.setGraphic(Icons.create("plus",16));add.setOnAction(e->addAccount(ctx));VBox list=new VBox(0);for(Account a:state.snapshot().accounts()){VBox id=new VBox(4,Ui.label(a.name(),"priority-title"),Ui.label(a.type().name()+(a.emergencyFund()?" · EMERGENCY FUND":""),"muted"));HBox.setHgrow(id,Priority.ALWAYS);Label amount=Ui.label(Money.inr(a.balance()),"debt-amount");HBox row=Ui.row(accountIcon(a.type()),id,amount);row.getStyleClass().add("priority-row");list.getChildren().add(row);}return new VBox(16,Ui.card(Ui.row(new VBox(4,Ui.label("ACCOUNTS","eyebrow"),Ui.label("Assets & balances","section-title")),Ui.spacer(),add),list),Ui.card(Ui.row(Ui.label("TOTAL ASSETS","eyebrow"),Ui.spacer(),Ui.label(Money.inr(state.snapshot().assets()),"stat-value")),Ui.label("Account balances are counted once in net worth. Transfers do not create income or expense.","body-copy")));}
    private static Node accountIcon(Account.AccountType type){StackPane icon=new StackPane(Ui.label(type.name().substring(0,1),"goal-letter"));icon.getStyleClass().addAll("goal-badge","goal-medium");return icon;}
    private static Node security(PageContext ctx){VBox root=new VBox(16);root.setPadding(new javafx.geometry.Insets(20,0,0,0));Button backup=Ui.button("Create backup","primary-button");backup.setOnAction(e->ctx.controller().execute(()->{Path path=ctx.controller().backups().backup();javafx.application.Platform.runLater(()->ctx.toast().accept("Backup created · "+path.getFileName()));},()->{},ctx.error()));Button restore=Ui.button("Restore backup","secondary-button");restore.setOnAction(e->restore(ctx));VBox backupCard=Ui.card(Ui.row(new VBox(4,Ui.label("LOCAL BACKUP","eyebrow"),Ui.label("Protect your workspace","section-title")),Ui.spacer(),backup,restore),Ui.label("Backups are timestamped ZIP files in FINORA's local app-data folder and are never overwritten automatically.","body-copy"));VBox guard=Ui.card(Ui.label("SECURITY BASELINE","eyebrow"),securityRow("Prepared statements","All variable database inputs are parameterized."),securityRow("Atomic operations","Transfers, debt payments and goal contributions use database transactions."),securityRow("No embedded secrets","MySQL credentials are not stored in source code or UI logs."),securityRow("Conflict-aware sync","Synchronization analysis surfaces conflicts instead of silently overwriting them."));return new VBox(16,backupCard,guard);}
    private static HBox securityRow(String title,String copy){VBox text=new VBox(4,Ui.label(title,"priority-title"),Ui.label(copy,"micro-copy"));return Ui.row(Ui.severityDot("healthy"),text);}
    private static VBox disclaimer(){Label text=Ui.label("FINORA distinguishes calculated facts from recommendations and assumptions. It does not guarantee returns or replace regulated financial advice.","body-copy");text.setWrapText(true);VBox box=Ui.card(Ui.label("FINANCIAL SAFETY","assumption-label"),text);box.getStyleClass().add("assumption-card");return box;}
    private static void connectMySql(PageContext ctx){Dialog<ButtonType>d=new Dialog<>();d.setTitle("Connect to MySQL");d.initOwner(ctx.owner().get());ButtonType connect=new ButtonType("Test & connect",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,connect);TextField host=new TextField("localhost");TextField port=new TextField("3306");TextField db=new TextField("finora");TextField user=new TextField();PasswordField password=new PasswordField();d.getDialogPane().setContent(new VBox(10,Ui.label("OPTIONAL CENTRAL STORAGE","eyebrow"),Ui.label("Connect to MySQL","dialog-title"),field("HOST",host),Ui.row(field("PORT",port),field("DATABASE",db)),field("USERNAME",user),field("PASSWORD",password),Ui.label("Use a least-privilege database user. Credentials remain in memory for this session.","assumption-label")));d.getDialogPane().lookupButton(connect).addEventFilter(javafx.event.ActionEvent.ACTION,e->{e.consume();try{MySQLConnectionProvider provider=new MySQLConnectionProvider(host.getText(),Integer.parseInt(port.getText()),db.getText(),user.getText(),password.getText().toCharArray());ctx.controller().execute(()->ctx.controller().database().use(provider),()->{d.close();ctx.toast().accept("Connected to MySQL");ctx.refresh().run();},ctx.error());}catch(Exception ex){ctx.error().accept(ex);}});d.showAndWait();}
    private static void addAccount(PageContext ctx){Dialog<ButtonType>d=new Dialog<>();d.setTitle("Add account");d.initOwner(ctx.owner().get());ButtonType save=new ButtonType("Add account",ButtonBar.ButtonData.OK_DONE);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,save);TextField name=new TextField();ComboBox<Account.AccountType> type=new ComboBox<>(FXCollections.observableArrayList(Account.AccountType.values()));type.getSelectionModel().select(Account.AccountType.CHECKING);TextField balance=new TextField("0");CheckBox emergency=new CheckBox("Count this account as emergency reserve");d.getDialogPane().setContent(new VBox(10,Ui.label("NEW ASSET ACCOUNT","eyebrow"),Ui.label("Add account","dialog-title"),field("ACCOUNT NAME",name),field("ACCOUNT TYPE",type),field("OPENING BALANCE",balance),emergency));d.getDialogPane().lookupButton(save).addEventFilter(javafx.event.ActionEvent.ACTION,e->{try{BigDecimal amount=new BigDecimal(balance.getText().replace(",",""));ctx.controller().execute(()->ctx.controller().finance().addAccount(name.getText(),type.getValue(),amount,emergency.isSelected()),()->{ctx.toast().accept("Account added");ctx.refresh().run();},ctx.error());}catch(Exception ex){e.consume();ctx.error().accept(ex);}});d.showAndWait();}
    private static void restore(PageContext ctx){try{var backups=ctx.controller().backups().list();if(backups.isEmpty()){new Alert(Alert.AlertType.INFORMATION,"No FINORA backups are available.",ButtonType.OK).showAndWait();return;}ChoiceDialog<Path>d=new ChoiceDialog<>(backups.getFirst(),backups);d.setTitle("Restore database");d.setHeaderText("Restore a local backup");d.setContentText("Backup:");d.initOwner(ctx.owner().get());d.showAndWait().ifPresent(path->{Alert confirm=new Alert(Alert.AlertType.CONFIRMATION,"Current local data will be replaced by "+path.getFileName()+".",ButtonType.CANCEL,ButtonType.OK);confirm.setHeaderText("Confirm database restore");confirm.showAndWait().filter(b->b==ButtonType.OK).ifPresent(b->ctx.controller().execute(()->ctx.controller().backups().restore(path),()->{ctx.toast().accept("Database restored");ctx.refresh().run();},ctx.error()));});}catch(Exception ex){ctx.error().accept(ex);}}
    private static VBox field(String label,Control input){input.setMaxWidth(Double.MAX_VALUE);VBox b=new VBox(7,Ui.label(label,"field-label"),input);HBox.setHgrow(b,Priority.ALWAYS);return b;}
}
