package com.finora.database;

import java.sql.*;
import java.time.Instant;
import java.util.List;

public final class DatabaseInitializer {
    private DatabaseInitializer() {
    }

    public static void initialize(ConnectionProvider provider) throws SQLException {
        try (Connection connection = provider.getConnection()) {
            connection.setAutoCommit(false);
            try {
                createSchema(connection, provider.type());
                removeLegacyDemoWorkspace(connection);
                ensureWorkspaceMode(connection);
                connection.commit();
            } catch (SQLException exception) {
                connection.rollback();
                throw exception;
            } finally {
                connection.setAutoCommit(true);
            }
        }
    }

    private static void createSchema(Connection connection, DatabaseType type) throws SQLException {
        String id = type == DatabaseType.H2
                ? "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                : "BIGINT AUTO_INCREMENT PRIMARY KEY";

        List<String> ddl = List.of(
                "CREATE TABLE IF NOT EXISTS users (id " + id + ", display_name VARCHAR(120) NOT NULL, username VARCHAR(80) NOT NULL UNIQUE, password_hash VARCHAR(160) NOT NULL, password_salt VARCHAR(80) NOT NULL, failed_attempts INT NOT NULL DEFAULT 0, locked_until TIMESTAMP NULL, last_login_at TIMESTAMP NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS auth_sessions (id " + id + ", user_id BIGINT NOT NULL, token_hash VARCHAR(160) NOT NULL, expires_at TIMESTAMP NOT NULL, last_used_at TIMESTAMP NOT NULL, revoked BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(id))",
                "CREATE TABLE IF NOT EXISTS ai_memory (id " + id + ", user_id BIGINT NOT NULL, memory_type VARCHAR(40) NOT NULL, memory_key VARCHAR(120) NOT NULL, memory_value VARCHAR(2000) NOT NULL, importance DECIMAL(5,2) NOT NULL DEFAULT 0.50, confidence DECIMAL(5,2) NOT NULL DEFAULT 1.00, last_used_at TIMESTAMP NOT NULL, deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_memory_user FOREIGN KEY (user_id) REFERENCES users(id), CONSTRAINT uq_ai_memory UNIQUE(user_id,memory_type,memory_key))",
                "CREATE TABLE IF NOT EXISTS ai_conversations (id " + id + ", user_id BIGINT NOT NULL, title VARCHAR(160) NOT NULL, deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_conversation_user FOREIGN KEY (user_id) REFERENCES users(id))",
                "CREATE TABLE IF NOT EXISTS ai_messages (id " + id + ", conversation_id BIGINT NOT NULL, role VARCHAR(20) NOT NULL, content VARCHAR(8000) NOT NULL, intent VARCHAR(50), tool_trace VARCHAR(4000), verified BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id))",
                "CREATE TABLE IF NOT EXISTS ai_settings (user_id BIGINT PRIMARY KEY, memory_enabled BOOLEAN NOT NULL DEFAULT TRUE, daily_briefing BOOLEAN NOT NULL DEFAULT TRUE, provider_type VARCHAR(40) NOT NULL DEFAULT 'DETERMINISTIC', model_name VARCHAR(120), endpoint VARCHAR(500), response_style VARCHAR(30) NOT NULL DEFAULT 'BALANCED', cloud_consent BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_ai_settings_user FOREIGN KEY (user_id) REFERENCES users(id))",
                "CREATE TABLE IF NOT EXISTS accounts (id " + id + ", user_id BIGINT NOT NULL, name VARCHAR(120) NOT NULL, account_type VARCHAR(30) NOT NULL, balance DECIMAL(19,2) NOT NULL DEFAULT 0, currency VARCHAR(3) NOT NULL DEFAULT 'INR', emergency_fund BOOLEAN NOT NULL DEFAULT FALSE, deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS income_sources (id " + id + ", user_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL, amount DECIMAL(19,2) NOT NULL CHECK (amount > 0), frequency VARCHAR(20) NOT NULL, next_income_date DATE NOT NULL, account_id BIGINT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, notes VARCHAR(1000), deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_income_account FOREIGN KEY (account_id) REFERENCES accounts(id))",
                "CREATE TABLE IF NOT EXISTS financial_transactions (id " + id + ", user_id BIGINT NOT NULL, amount DECIMAL(19,2) NOT NULL CHECK (amount > 0), tx_type VARCHAR(40) NOT NULL, category VARCHAR(80) NOT NULL, account_id BIGINT NOT NULL, related_account_id BIGINT NULL, tx_date DATE NOT NULL, description VARCHAR(240) NOT NULL, notes VARCHAR(1000), reference_id BIGINT NULL, deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT fk_tx_account FOREIGN KEY (account_id) REFERENCES accounts(id))",
                "CREATE TABLE IF NOT EXISTS debts (id " + id + ", user_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL, debt_type VARCHAR(40) NOT NULL, original_amount DECIMAL(19,2) NOT NULL, remaining_amount DECIMAL(19,2) NOT NULL CHECK (remaining_amount >= 0), interest_rate DECIMAL(9,4) NOT NULL DEFAULT 0, minimum_payment DECIMAL(19,2) NOT NULL DEFAULT 0, due_date DATE, user_priority INT NOT NULL DEFAULT 3, relationship_importance INT NOT NULL DEFAULT 3, penalty_risk BOOLEAN NOT NULL DEFAULT FALSE, notes VARCHAR(1000), deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS goals (id " + id + ", user_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL, target_amount DECIMAL(19,2) NOT NULL, current_amount DECIMAL(19,2) NOT NULL DEFAULT 0, monthly_contribution DECIMAL(19,2) NOT NULL DEFAULT 0, deadline DATE, priority VARCHAR(20) NOT NULL, notes VARCHAR(1000), deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS bills (id " + id + ", user_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL, category VARCHAR(80) NOT NULL, amount DECIMAL(19,2) NOT NULL, due_date DATE NOT NULL, recurring BOOLEAN NOT NULL DEFAULT FALSE, frequency VARCHAR(30), paid BOOLEAN NOT NULL DEFAULT FALSE, subscription BOOLEAN NOT NULL DEFAULT FALSE, last_used_date DATE, deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS investments (id " + id + ", user_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL, category VARCHAR(80) NOT NULL, current_value DECIMAL(19,2) NOT NULL DEFAULT 0, monthly_contribution DECIMAL(19,2) NOT NULL DEFAULT 0, notes VARCHAR(1000), deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS budgets (id " + id + ", user_id BIGINT NOT NULL, category VARCHAR(80) NOT NULL, limit_amount DECIMAL(19,2) NOT NULL, month_key VARCHAR(7) NOT NULL, deleted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT uq_budget_user UNIQUE(user_id, category, month_key))",
                "CREATE TABLE IF NOT EXISTS net_worth_history (id " + id + ", user_id BIGINT NOT NULL, snapshot_date DATE NOT NULL, assets DECIMAL(19,2) NOT NULL, liabilities DECIMAL(19,2) NOT NULL, net_worth DECIMAL(19,2) NOT NULL, created_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS app_settings (setting_key VARCHAR(120) PRIMARY KEY, setting_value VARCHAR(2000), updated_at TIMESTAMP NOT NULL)",
                "CREATE TABLE IF NOT EXISTS sync_changelog (id " + id + ", user_id BIGINT NOT NULL, entity_type VARCHAR(60) NOT NULL, entity_id BIGINT NOT NULL, operation VARCHAR(20) NOT NULL, changed_at TIMESTAMP NOT NULL, synced BOOLEAN NOT NULL DEFAULT FALSE)"
        );

        try (Statement statement = connection.createStatement()) {
            for (String sql : ddl) {
                statement.execute(sql);
            }
        }
        ensureColumn(connection, "ai_messages", "tool_trace", "VARCHAR(4000)");
        ensureColumn(connection, "ai_messages", "verified", "BOOLEAN NOT NULL DEFAULT FALSE");
        ensureColumn(connection, "ai_settings", "response_style", "VARCHAR(30) NOT NULL DEFAULT 'BALANCED'");
        ensureColumn(connection, "ai_settings", "cloud_consent", "BOOLEAN NOT NULL DEFAULT FALSE");
        migrateFinancialOwnership(connection, type);
        createIndexIfMissing(connection, "financial_transactions", "idx_tx_date", "tx_date");
        createIndexIfMissing(connection, "financial_transactions", "idx_tx_type", "tx_type");
        createIndexIfMissing(connection, "income_sources", "idx_income_next_date", "next_income_date");
        createIndexIfMissing(connection, "users", "idx_users_username", "username");
        createIndexIfMissing(connection, "auth_sessions", "idx_session_user", "user_id");
        createIndexIfMissing(connection, "ai_memory", "idx_memory_user", "user_id");
        createIndexIfMissing(connection, "ai_conversations", "idx_conversation_user", "user_id");
        createIndexIfMissing(connection, "ai_messages", "idx_message_conversation", "conversation_id");
        for (String table : FINANCIAL_OWNER_TABLES) {
            createIndexIfMissing(connection, table, "idx_" + table + "_user", "user_id");
        }
        createCompositeIndexIfMissing(connection, "budgets", "uq_budget_scope",
                "user_id,category,month_key", true);
    }

    private static final List<String> FINANCIAL_OWNER_TABLES = List.of(
            "accounts", "income_sources", "financial_transactions", "debts", "goals", "bills",
            "investments", "budgets", "net_worth_history", "sync_changelog");

    /**
     * Versions before local sign-in shipped a sample workspace. It was explicitly marked
     * with workspace_mode=DEMO. Only that marked dataset is removed; real unmarked data
     * is never guessed at or deleted.
     */
    private static void removeLegacyDemoWorkspace(Connection connection) throws SQLException {
        String mode = setting(connection, "workspace_mode");
        if (!"DEMO".equalsIgnoreCase(mode)) {
            return;
        }
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("DELETE FROM financial_transactions");
            statement.executeUpdate("DELETE FROM income_sources");
            statement.executeUpdate("DELETE FROM debts");
            statement.executeUpdate("DELETE FROM goals");
            statement.executeUpdate("DELETE FROM bills");
            statement.executeUpdate("DELETE FROM investments");
            statement.executeUpdate("DELETE FROM budgets");
            statement.executeUpdate("DELETE FROM net_worth_history");
            statement.executeUpdate("DELETE FROM sync_changelog");
            statement.executeUpdate("DELETE FROM accounts");
        }
        try (PreparedStatement update = connection.prepareStatement(
                "UPDATE app_settings SET setting_value=?, updated_at=? WHERE setting_key=?")) {
            update.setString(1, "EMPTY");
            update.setTimestamp(2, Timestamp.from(Instant.now()));
            update.setString(3, "workspace_mode");
            update.executeUpdate();
        }
    }

    private static void ensureWorkspaceMode(Connection connection) throws SQLException {
        if (setting(connection, "workspace_mode") != null) {
            return;
        }
        try (PreparedStatement insert = connection.prepareStatement(
                "INSERT INTO app_settings(setting_key,setting_value,updated_at) VALUES(?,?,?)")) {
            insert.setString(1, "workspace_mode");
            insert.setString(2, "EMPTY");
            insert.setTimestamp(3, Timestamp.from(Instant.now()));
            insert.executeUpdate();
        }
    }

    private static String setting(Connection connection, String key) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT setting_value FROM app_settings WHERE setting_key=?")) {
            statement.setString(1, key);
            try (ResultSet result = statement.executeQuery()) {
                return result.next() ? result.getString(1) : null;
            }
        }
    }

    /** Assigns every pre-profile financial record to the original owner exactly once. */
    private static void migrateFinancialOwnership(Connection connection, DatabaseType type) throws SQLException {
        for (String table : FINANCIAL_OWNER_TABLES) {
            ensureColumn(connection, table, "user_id", "BIGINT NULL");
        }
        dropLegacyBudgetConstraint(connection, type);

        Long originalOwner = null;
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT id FROM users WHERE active=TRUE ORDER BY created_at,id");
             ResultSet result = statement.executeQuery()) {
            if (result.next()) originalOwner = result.getLong(1);
        }
        if (originalOwner != null) {
            for (String table : FINANCIAL_OWNER_TABLES) {
                try (PreparedStatement update = connection.prepareStatement(
                        "UPDATE " + table + " SET user_id=? WHERE user_id IS NULL")) {
                    update.setLong(1, originalOwner);
                    update.executeUpdate();
                }
            }
        }
        for (String table : FINANCIAL_OWNER_TABLES) {
            if (!hasNullOwner(connection, table)) makeOwnerRequired(connection, type, table);
        }
    }

    private static boolean hasNullOwner(Connection connection, String table) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM " + table + " WHERE user_id IS NULL")) {
            result.next();
            return result.getLong(1) > 0;
        }
    }

    private static void makeOwnerRequired(Connection connection, DatabaseType type, String table) throws SQLException {
        int nullable = DatabaseMetaData.columnNullableUnknown;
        try (ResultSet result = connection.getMetaData().getColumns(connection.getCatalog(), null, table, "user_id")) {
            if (result.next()) nullable = result.getInt("NULLABLE");
        }
        if (nullable == DatabaseMetaData.columnNoNulls) return;
        String sql = type == DatabaseType.H2
                ? "ALTER TABLE " + table + " ALTER COLUMN user_id SET NOT NULL"
                : "ALTER TABLE " + table + " MODIFY user_id BIGINT NOT NULL";
        try (Statement statement = connection.createStatement()) { statement.execute(sql); }
    }

    private static void dropLegacyBudgetConstraint(Connection connection, DatabaseType type) throws SQLException {
        if (type == DatabaseType.H2) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("ALTER TABLE budgets DROP CONSTRAINT IF EXISTS uq_budget");
            }
        } else if (indexExists(connection, "budgets", "uq_budget")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("ALTER TABLE budgets DROP INDEX uq_budget");
            }
        }
    }

    private static void ensureColumn(Connection connection, String table, String column, String definition)
            throws SQLException {
        boolean exists = false;
        try (ResultSet result = connection.getMetaData().getColumns(connection.getCatalog(), null, table, column)) {
            exists = result.next();
        }
        if (!exists) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition);
            }
        }
    }

    private static boolean indexExists(Connection connection, String table, String index) throws SQLException {
        try (ResultSet result = connection.getMetaData().getIndexInfo(
                connection.getCatalog(), null, table, false, false)) {
            while (result.next()) {
                String existing = result.getString("INDEX_NAME");
                if (existing != null && existing.equalsIgnoreCase(index)) return true;
            }
        }
        return false;
    }

    private static void createIndexIfMissing(Connection connection, String table, String index, String column)
            throws SQLException {
        if (!indexExists(connection, table, index)) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("CREATE INDEX " + index + " ON " + table + "(" + column + ")");
            }
        }
    }

    private static void createCompositeIndexIfMissing(Connection connection, String table, String index,
                                                       String columns, boolean unique) throws SQLException {
        if (!indexExists(connection, table, index)) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("CREATE " + (unique ? "UNIQUE " : "") + "INDEX " + index +
                        " ON " + table + "(" + columns + ")");
            }
        }
    }
}
